### ISSUE TITLE
Unhandled exception in the UI thread

### ISSUE THREAD

**Issue by GainLee** [google/agi#1081] opened 2022-04-13 09:53 UTC
**Environment information:**
 - AGI version: 2022-3.0.0
 - Host OS: MacOS
 If tracing on Android:
 - Device model: Pixel4
 - Android Version: 12

**Bug description**
An error dialog

**Reproduction steps**
On Performance tab, click CommandBuffer->RenderPass->Draw

**Stacktrace**
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.NullPointerException)
	at org.eclipse.swt.SWT.error(SWT.java:4893)
	at org.eclipse.swt.SWT.error(SWT.java:4808)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:188)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4262)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3885)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at com.google.gapid.Main$UI.show(Main.java:140)
	at com.google.gapid.Main.main(Main.java:80)
Caused by: java.lang.NullPointerException
	at com.google.gapid.models.Resources.loadResourceExtras(Resources.java:168)
	at com.google.gapid.views.ShaderView$ShaderWidget.setShader(ShaderView.java:284)
	at com.google.gapid.views.PipelineView.createStage(PipelineView.java:535)
	at com.google.gapid.views.PipelineView.createPipelineTabs(PipelineView.java:241)
	at com.google.gapid.views.PipelineView.setPipelines(PipelineView.java:214)
	at com.google.gapid.views.PipelineView$1.onUiThreadSuccess(PipelineView.java:200)
	at com.google.gapid.views.PipelineView$1.onUiThreadSuccess(PipelineView.java:171)
	at com.google.gapid.rpc.UiErrorCallback.onUiThread(UiErrorCallback.java:34)
	at com.google.gapid.rpc.UiErrorCallback.onUiThread(UiErrorCallback.java:25)
	at com.google.gapid.rpc.UiCallback.lambda$onFinish$0(UiCallback.java:46)
	at com.google.gapid.widgets.Widgets.ifNotDisposed(Widgets.java:141)
	at com.google.gapid.widgets.Widgets.lambda$scheduleIfNotDisposed$1(Widgets.java:169)
	at com.google.gapid.widgets.Widgets.lambda$schedule$0(Widgets.java:161)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	... 6 more

**Screenshots**
<img width="694" alt="image" src="https://user-images.githubusercontent.com/2909095/163151377-c5296c85-1df4-4496-ae4f-f1ef237e0726.png">

**Additional debugging information**
- None

**Comment by ttanatb** [comment] 2022-04-13 14:33
Hi, thanks for reporting this issue! We're working on a fix to this (https://github.com/google/agi/pull/1076) but here's the current workaround https://github.com/google/agi/issues/1074#issuecomment-1091849765

**Comment by pmuetschard** [comment] 2022-04-15 16:30
Duplicate of #1074

**Closed by pmuetschard** 2022-04-15 16:30 UTC
