### ISSUE TITLE
Pixel 6 fails validation: Failed to initialize HWC reader

### ISSUE THREAD

**Issue by prodigga** [google/agi#1070] opened 2022-03-27 02:52 UTC
**Environment information:**
 - AGI version: 3.0.0
 - Host OS: [e.g. Linux] Windows
 If tracing on Android:
 - Device model: Google Pixel 6
 - Android Version: Android 12 API 31

**Bug description**
Fails validation

**Reproduction steps**
Connect device and validate. It fails.

**Stacktrace**
N/a

**Screenshots**
![image](https://user-images.githubusercontent.com/185220/160264608-7797ad96-3829-4514-9c63-f638983f9aa5.png)

**Comment by ttanatb** [comment] 2022-03-28 13:37
Thanks for reporting this. Could you also attach the trace file along with `gapic.log` or `gapis.log` to the github issue as well?

**Comment by pengdev** [comment] 2022-06-08 11:34
@ttanatb I have seen the same issue on my Pixel 6 Pro, please see the attached log files:
[gapis.log](https://github.com/google/agi/files/8861113/gapis.log)
[gapic.log](https://github.com/google/agi/files/8861114/gapic.log)

**Comment by ttanatb** [comment] 2022-06-08 11:59
Thanks for the additional info, but could you also provide the trace file as well? The link from `View trace file` should show you the specific trace file in the tmp folder

**Comment by pengdev** [comment] 2022-06-08 12:13
@ttanatb here's the trace file and logcat
[validation2187746757.perfetto.zip](https://github.com/google/agi/files/8861391/validation2187746757.perfetto.zip)
[logcat.txt](https://github.com/google/agi/files/8861398/logcat.txt)

**Comment by timbo-tj** [comment] 2022-06-09 21:33
Pengdev's experience mirrors mine exactly with my Pixel 6 (not Pro).

**Comment by prodigga** [comment] 2022-06-18 07:06
Hello, (timbo-tj here, different account)

Validation passes on my workstation at work, but can confirm it still fails here at home. Maybe something wrong with the USB cable I am using? Or something wrong with my system? Unsure.

**Comment by ttanatb** [comment] 2022-06-20 10:45
It depends on the error message you're getting. If it's same/similar to the one you posted in the original screenshot, the error is likely to be caused by the phone itself, not the system you're running AGI on. It's also unlikely that it's due to a faulty USB cable (especially if AGI is able to detect the phone in the first place).

I've seen other validation errors occur due to a bad installation, but not with the error message you are seeing.

**Comment by ttanatb** [comment] 2023-02-27 14:28
Hello, is this still an issue for Pixel 6 devices? (I haven't been able to repro on my end)

**Comment by amaroney55** [comment] 2023-08-06 14:27
Hey I am just gonna butt in and ask.  How in the world do you get the pixel 6 pro out of pixel rom recovery (exynos USB boot mode) it is hard bricked and it will register on PC as USB serial device only. Will not go into adb/fastboot mode. Sorry for being rude and jumping in. But I have been working with this issue since 2nd a14 beta. And apparently a lot of other ppl has to. I think there might be a way to boot the phone back to working state with uwb mode from reading a lot of info bout that but it doesn't really say if you can or can't. And I am not comfortable with doing any work with the USB serial communication yet. I really just now have learned a little about jtag and uart. But if you can help please do.

**Comment by olehkuznetsov** [comment] 2024-12-20 13:18
Fixed with 3.3.2

**Closed by olehkuznetsov** 2024-12-20 13:18 UTC
Labels: Needs more information
