### ISSUE TITLE
Device Connection Failed---SamSung S10

### ISSUE THREAD

**Issue by JackKaiXing** [google/agi#1250] opened 2022-12-02 14:55 UTC
Like someone posted here, https://github.com/google/agi/issues/1131

On my SamSung S10

adb shell "echo 1 > /sys/class/kgsl/kgsl-3d0/perfcounter"
/system/bin/sh: can't create /sys/class/kgsl/kgsl-3d0/perfcounter: Permission denied

**Comment by JackKaiXing** [comment] 2022-12-02 14:57
Android 12, One UI 4.1. It worked before but now could not be connected.

**Comment by ttanatb** [comment] 2022-12-05 15:37
What's the build number where you encountered this issue? (Search for build number in `settings`)

**Comment by ttanatb** [comment] 2022-12-20 17:24
Closing this because it looks like a duplicate of #1252 
If this is not the case, please re-open with more info

**Closed by ttanatb** 2022-12-20 17:24 UTC
