### ISSUE TITLE
Pixel 7 fails validation - Passed 0 out of 6 checks

### ISSUE THREAD

**Issue by DethRaid** [google/agi#1273] opened 2023-02-13 01:45 UTC
**Environment information:**
 - AGI version: 2023-3.3.0
 - Host OS: Windows 11
 If tracing on Android:
 - Device model: Pixel 7
 - Android Version: 13 (build number TD1A.221105.001)

**Bug description**
When I open AGI to try and profile an application on my device, AGI reports that my device fails validation. It opens the test app with the spinning cube without issue, but AGI reports a FailedTraceValidationError

**Reproduction steps**
- Connect a Pixel 7 to your compute
- Open AGI
- Try to either capture a system trace or capture a frame
- Wait for the test app to finish displaying the spinning cube
- Observe that the device failed validation

**Stacktrace**
Stack trace from Android logs:
```
Build fingerprint: 'google/panther/panther:13/TD1A.221105.001/9104446:user/release-keys'
Revision: 'MP1.0'
ABI: 'arm64'
Timestamp: 2023-02-12 17:39:15.527394889-0800
Process uptime: 4s
Cmdline: /data/local/tmp/agi_launch_producer
pid: 5765, tid: 5767, name: agi_launch_prod  >>> /data/local/tmp/agi_launch_producer <<<
uid: 2000
tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000000000000000
Cause: null pointer dereference
    x0  0000000000000000  x1  0000000000000053  x2  000000778a1ae150  x3  00000076e7833468
    x4  0000000000000018  x5  b40000781a1a685c  x6  b40000781a1a67b0  x7  0000000002faf080
    x8  00000076e7833510  x9  0000000000000001  x10 0000000000000002  x11 0000000000000018
    x12 000000000000c4ed  x13 0000000000000020  x14 0000000000000007  x15 0000000000000000
    x16 00000076e79e57c0  x17 000000797a264b00  x18 00000076e736e000  x19 b40000787a1acd50
    x20 b40000787a1acd68  x21 00000076e78335b0  x22 00000076e7838010  x23 b40000787a1ad1ac
    x24 ffffffff00000000  x25 ffffffff02faf080  x26 00000076e7833618  x27 00000076e7833618
    x28 b4000077ba1a62c8  x29 b40000778a1ae218
    lr  00000076e79691d0  sp  00000076e7833510  pc  00000076e796c660  pst 00000000a0001000
backtrace:
      #00 pc 0000000000130660  /vendor/lib64/libgpudataproducer.so (base_hwcnt_reader_get_metadata+0) (BuildId: bd128c82d7de0c51)
      #01 pc 000000000012d1cc  /vendor/lib64/libgpudataproducer.so (periodic_hwc_reader::periodic_hwc_reader(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> >, std::__1::error_code&)+204) (BuildId: bd128c82d7de0c51)
      #02 pc 000000000012e330  /vendor/lib64/libgpudataproducer.so (mali_gpu_data_source::OnSetup(perfetto::DataSourceBase::SetupArgs const&)+736) (BuildId: bd128c82d7de0c51)
      #03 pc 00000000001589d4  /vendor/lib64/libgpudataproducer.so (perfetto::internal::TracingMuxerImpl::SetupDataSource(unsigned long, unsigned int, unsigned long, perfetto::protos::gen::DataSourceConfig const&)+1140) (BuildId: bd128c82d7de0c51)
      #04 pc 0000000000186ff8  /vendor/lib64/libgpudataproducer.so (perfetto::ProducerIPCClientImpl::OnServiceRequest(perfetto::protos::gen::GetAsyncCommandResponse const&)+520) (BuildId: bd128c82d7de0c51)
      #05 pc 000000000019660c  /vendor/lib64/libgpudataproducer.so (std::__1::__function::__func<perfetto::ProducerIPCClientImpl::OnConnect()::$_122, std::__1::allocator<perfetto::ProducerIPCClientImpl::OnConnect()::$_122>, void (perfetto::ipc::AsyncResult<perfetto::protos::gen::GetAsyncCommandResponse>)>::operator()(perfetto::ipc::AsyncResult<perfetto::protos::gen::GetAsyncCommandResponse>&&)+28) (BuildId: bd128c82d7de0c51)
      #06 pc 0000000000196538  /vendor/lib64/libgpudataproducer.so (std::__1::__function::__func<perfetto::ipc::Deferred<perfetto::protos::gen::GetAsyncCommandResponse>::Bind(std::__1::function<void (perfetto::ipc::AsyncResult<perfetto::protos::gen::GetAsyncCommandResponse>)>)::'lambda'(perfetto::ipc::AsyncResult<protozero::CppMessageObj>), std::__1::allocator<perfetto::ipc::Deferred<perfetto::protos::gen::GetAsyncCommandResponse>::Bind(std::__1::function<void (perfetto::ipc::AsyncResult<perfetto::protos::gen::GetAsyncCommandResponse>)>)::'lambda'(perfetto::ipc::AsyncResult<protozero::CppMessageObj>)>, void (perfetto::ipc::AsyncResult<protozero::CppMessageObj>)>::operator()(perfetto::ipc::AsyncResult<protozero::CppMessageObj>&&)+56) (BuildId: bd128c82d7de0c51)
      #07 pc 000000000017810c  /vendor/lib64/libgpudataproducer.so (perfetto::ipc::ServiceProxy::EndInvoke(unsigned long, std::__1::unique_ptr<protozero::CppMessageObj, std::__1::default_delete<protozero::CppMessageObj> >, bool)+140) (BuildId: bd128c82d7de0c51)
      #08 pc 0000000000177ec0  /vendor/lib64/libgpudataproducer.so (perfetto::ipc::ClientImpl::OnInvokeMethodReply(perfetto::ipc::ClientImpl::QueuedRequest, perfetto::protos::gen::IPCFrame_InvokeMethodReply const&)+272) (BuildId: bd128c82d7de0c51)
      #09 pc 00000000001778cc  /vendor/lib64/libgpudataproducer.so (perfetto::ipc::ClientImpl::OnFrameReceived(perfetto::protos::gen::IPCFrame const&)+364) (BuildId: bd128c82d7de0c51)
      #10 pc 00000000001775c4  /vendor/lib64/libgpudataproducer.so (perfetto::ipc::ClientImpl::OnDataAvailable(perfetto::base::UnixSocket*)+260) (BuildId: bd128c82d7de0c51)
      #11 pc 0000000000175234  /vendor/lib64/libgpudataproducer.so (perfetto::base::UnixSocket::OnEvent()+276) (BuildId: bd128c82d7de0c51)
      #12 pc 000000000013960c  /vendor/lib64/libgpudataproducer.so (perfetto::base::UnixTaskRunner::RunFileDescriptorWatch(int)+572) (BuildId: bd128c82d7de0c51)
      #13 pc 00000000001391bc  /vendor/lib64/libgpudataproducer.so (perfetto::base::UnixTaskRunner::RunImmediateAndDelayedTask()+812) (BuildId: bd128c82d7de0c51)
      #14 pc 00000000001387c0  /vendor/lib64/libgpudataproducer.so (perfetto::base::UnixTaskRunner::Run()+368) (BuildId: bd128c82d7de0c51)
      #15 pc 0000000000138268  /vendor/lib64/libgpudataproducer.so (perfetto::base::ThreadTaskRunner::RunTaskThread(std::__1::function<void (perfetto::base::UnixTaskRunner*)>)+440) (BuildId: bd128c82d7de0c51)
      #16 pc 000000000018b95c  /vendor/lib64/libgpudataproducer.so (void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (perfetto::base::ThreadTaskRunner::*)(std::__1::function<void (perfetto::base::UnixTaskRunner*)>), perfetto::base::ThreadTaskRunner*, std::__1::function<void (perfetto::base::UnixTaskRunner*)> > >(void*)+172) (BuildId: bd128c82d7de0c51)
      #17 pc 00000000000c14dc  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204) (BuildId: cbc4c62a9b269839456f1d7728d8411e)
      #18 pc 0000000000054930  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: cbc4c62a9b269839456f1d7728d8411e)

```

**Screenshots**
![image](https://user-images.githubusercontent.com/2505597/218352323-fad8a82f-e453-4a86-a7d1-a35f7f13f2bc.png)

**Additional debugging information**
[gapis.log](https://github.com/google/agi/files/10717946/gapis.log)

[gapic.log](https://github.com/google/agi/files/10717945/gapic.log)

[logcat-full.txt](https://github.com/google/agi/files/10717949/logcat-full.txt)

**Comment by ttanatb** [comment] 2023-02-13 12:53
Thanks for raising this issue! This looks like a duplicate of https://github.com/google/agi/issues/1234 which has been fixed internally but we're still waiting for the release patch. Additional details in the original bug

**Closed by ttanatb** 2023-02-13 12:53 UTC

**Comment by DethRaid** [comment] 2023-02-13 20:28
Oh. I thought it might be a different issue since I got a different error message than #1234. I'll wait for the next release
