### ISSUE TITLE
The application exited during the capture

### ISSUE THREAD

**Issue by ddubois-itoys** [google/agi#1025] opened 2022-02-01 17:40 UTC
**Environment information:**
 - AGI version:
 - Host OS: Window 10
 If tracing on Android:
 - Device model: Samsung S21 5G SM-G991B/DS
 - Android Version: 11

**Bug description**
My application crashes whenever I try to capture a profiling trace on my S21

**Reproduction steps**
- Connect a Samsung S21 to your computer
- Select "Capture a New Trace" in AGI
- Select your device and application in AGI, leave everything else at default settings
- Click OK
- My application opens on my phone, starts initializing, then closes. AGI pops up an error window with a stack trace

**Stacktrace**
```
com.google.gapid.server.Client$InternalServerErrorException: Tracing Failed
   Cause: The application exited during the capture
   Cause: EOF
	at com.google.gapid.server.Client.throwIfError(Client.java:327)
	at com.google.gapid.server.Client.lambda$streamTrace$58(Client.java:301)
	at com.google.gapid.server.GapidClientGrpc$StreamHandler.onNext(GapidClientGrpc.java:232)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:465)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInternal(ClientCallImpl.java:656)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:641)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.google.gapid.server.Client$Stack: For request: RPC->streamTrace()
	at com.google.gapid.server.Client.streamTrace(Client.java:298)
	at com.google.gapid.server.Tracer.trace(Tracer.java:41)
	at com.google.gapid.views.TracerDialog.showTracingDialog(TracerDialog.java:188)
	at com.google.gapid.LoadingScreen.lambda$createOptions$0(LoadingScreen.java:119)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4237)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4054)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at com.google.gapid.Main$UI.show(Main.java:136)
	at com.google.gapid.Main.main(Main.java:80)
```

**Screenshots**
N/A

**Additional debugging information**
- I've tried both enabling and disabling buffering, clear package cache, and include unsupported extension in the AGI settings, no change
- Please attach the generated _gapis.log_ and _gapic.log_ files you will find in the temp folder (e.g. /tmp/ on linux).
[gapic.log](https://github.com/google/agi/files/7980694/gapic.log)
[gapis.log](https://github.com/google/agi/files/7980695/gapis.log)
I've sanitized both files by replacing sensitive information with things like `${USER_HOME}` 

- If using Android: Please attach a full logcat dump (```adb logcat -d > logcat-full.txt```) that contains logs since AGI was started.
This is a proprietary project, there's no way I'll get permission to post the full device logs on a public forum like this. We'd have to figure out a secure communication channel for me to send those logs

**Comment by DethRaid** [comment] 2022-02-01 17:41
Note: unlike #1023 , my device passes AGI's validation checks

**Comment by ddubois-itoys** [comment] 2022-02-01 17:42
Note: unlike #1023 , my device passes AGI's validation checks

**Comment by tjudemon** [comment] 2022-04-07 08:13
My S20+ and S21 both showed The application encountered an error: Unhandled exception in the UI thread.

org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.NullPointerException)
	at org.eclipse.swt.SWT.error(SWT.java:4893)
	at org.eclipse.swt.SWT.error(SWT.java:4808)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:188)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4029)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3629)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at com.google.gapid.Main$UI.show(Main.java:140)
	at com.google.gapid.Main.main(Main.java:80)
Caused by: java.lang.NullPointerException
	at com.google.gapid.models.Resources.loadResourceExtras(Resources.java:168)
	at com.google.gapid.views.ShaderView$ShaderWidget.setShader(ShaderView.java:284)
	at com.google.gapid.views.PipelineView.createStage(PipelineView.java:535)
	at com.google.gapid.views.PipelineView.createPipelineTabs(PipelineView.java:241)
	at com.google.gapid.views.PipelineView.setPipelines(PipelineView.java:214)
	at com.google.gapid.views.PipelineView$1.onUiThreadSuccess(PipelineView.java:200)
	at com.google.gapid.views.PipelineView$1.onUiThreadSuccess(PipelineView.java:171)
	at com.google.gapid.rpc.UiErrorCallback.onUiThread(UiErrorCallback.java:34)
	at com.google.gapid.rpc.UiErrorCallback.onUiThread(UiErrorCallback.java:25)
	at com.google.gapid.rpc.UiCallback.lambda$onFinish$0(UiCallback.java:46)
	at com.google.gapid.widgets.Widgets.ifNotDisposed(Widgets.java:141)
	at com.google.gapid.widgets.Widgets.lambda$scheduleIfNotDisposed$1(Widgets.java:169)
	at com.google.gapid.widgets.Widgets.lambda$schedule$0(Widgets.java:161)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	... 6 more

**Comment by ttanatb** [comment] 2022-05-31 15:53
Hi, sorry for the late response -- thanks for filing this!

The trace looks like an issue we've resolved recently -- please let me know if you're still running into similar issues with the newest [release](https://github.com/google/agi/releases)

**Comment by ttanatb** [comment] 2022-06-23 13:57
The UI crash in this [comment](https://github.com/google/agi/issues/1025#issuecomment-1091269067) has been fixed. The EOF from this [comment](https://github.com/google/agi/issues/1025#issue-1121010537) might be caused by the specific game -- would need more information to debug/triage

**Comment by ttanatb** [comment] 2023-02-27 14:13
Closing this due to staleness -- feel free to reopen

**Closed by ttanatb** 2023-02-27 14:13 UTC
Labels: Needs more information
