### ISSUE TITLE
GLES draw calls outside of render pass in command tree

### ISSUE THREAD

**Issue by ianelliottus** [google/agi#758] opened 2021-04-08 22:06 UTC
**Environment information:**
 - AGI version: 1.1.0:dev-20210318
 - Host OS: Linux
 If tracing on Android:
 - Device model: Pixel 4 XL
 - Android Version: Android 11/RQ2A.210305.006

**Bug description**

The following games show GLES draw calls outside of render pass in command tree:
- Dota Underlords (com.valvesoftware.underlords) (original bug: b/178460111)
- PUBG MOBILE (com.tencent.ig) (original bug: b/175817130)
- Hill Climb Racing (com.fingersoft.hillclimb) (same original bug as PUBG)
- Real Gangster Crime (com.gta.real.gangster.crime) (same original bug as PUBG)

**Reproduction steps**

- Open the attached trace file for PUBG MOBILE
- Click to open up the 2nd "vkQueueSubmit" part of the hierarchy
- Click to open up the "pSubmits[0]" under that
- Click to open up the "Command Buffer" under that
- Observe that there are two RenderPass's with a number of glDrawElements between them. The hierarchy looks like the following:
  - Host Coordination
  - vkQueueSubmit
  - Host Coordination
  - vkQueueSubmit
    - pSubmits[0]
      - Command Buffer
        - vkCmdPipelineBarrier
        - RenderPass
          - vkCmdBeginRenderPass
          - vkCmdEndDebugUtilsLabelEXT // Looks like this was misplaced
        - vkCmdEndDebugUtilsLabelEXT // Looks like this was misplaced
        - vkCmdEndDebugUtilsLabelEXT // Looks like this was misplaced
        - glDrawElements
        - ... // Several glDrawElements
        - glDrawElements
        - vkCmdEndRenderPass
        - vkCmdPipelineBarrier
        - vkCmdPipelineBarrier
        - vkCmdPipelineBarrier
        - RenderPass
          - vkCmdBeginRenderPass
          - glDrawElements
          - ... // Lots of glDrawElements
          - glDrawElements
          - vkCmdEndRenderPass
  - Host Coordination
  - vkQueuePresentKHR

**Links to AGI Traces**

- PUBG trace for repro instructions: https://drive.google.com/file/d/1KZfCpo9zQv82odub7M4wtNTIFBWKLZKw/view?usp=sharing
- Real Gangster Crime trace: https://drive.google.com/file/d/1rL5LLcHSc9qEpqLVJR5tVjn62OvK281n/view?usp=sharing
- Hill Climb trace: https://drive.google.com/file/d/1nqEanSUNc7d2k_0EfClKvlCdIkqpPgpU/view?usp=sharing

**Comment by mark-lunarg** [comment] 2021-05-03 17:56
@ianelliottus, we are seeing unbalanced `vkCmdBeginDebugUtilsLabelEXT()`/`vkCmdEndDebugUtilsLabelEXT()` call pairs coming from ANGLE.  In Hillclimb, each frame appears to have a two unmatched `vkCmdEndDebugUtilsLabelEXT()` calls which can explain the resulting command tree that is produced in AGI.  If it will be helpful I can try to narrow down _where_ the mismatch is occurring.

**Comment by ianelliottus** [comment] 2021-05-03 19:49
@mark-lunarg since the ANGLE code is fairly contained and since you can see both sides (ANGLE and AGI), I'd like you to try to fix this in ANGLE.  The ANGLE code is located in the following methods:

- [ContextVk::logEvent](https://source.chromium.org/chromium/chromium/src/+/master:third_party/angle/src/libANGLE/renderer/vulkan/ContextVk.cpp;l=2966)
  - This is called for each GLES command
  - It stores the string for use when a draw/dispatch command is called
- [ContextVk::handleDirtyEventLogImpl](https://source.chromium.org/chromium/chromium/src/+/master:third_party/angle/src/libANGLE/renderer/vulkan/ContextVk.cpp;l=1274)
  - At the beginning of a draw/dispatch call, this processes all of the stored GLES calls (from above) and creates the hierarch of begin/end debug util markers
- [ContextVk::endEventLog](https://source.chromium.org/chromium/chromium/src/+/master:third_party/angle/src/libANGLE/renderer/vulkan/ContextVk.cpp;l=2981)
  - At the end of a draw/dispatch call, this adds a final end debug util marker

This should help with working on other hierarchy bugs (forgetting what one is, and another I need to port to GitHub:-)

**Comment by mark-lunarg** [comment] 2021-05-12 01:26
The  command tree representation relies on balanced pairs of `CmdBeginDebugUtilsLabelEXT()` and `CmdEndDebugUtilsLabelEXT() ` commands.  This AGI misbehavior is due to an imbalance resulting from 'missing' `CmdBeginDebugUtilsLabelEXT` calls. 

The first-level `CmdBeginDebugUtilsLabelEXT` commands are generated in `ContextVk::handleDirtyEventLogImpl()`, triggered by dirty bits ultimately set by each glDraw* handler (in `ContextVk::logEvent()`).  However, the corresponding and balancing `CmdEndDebugUtilsLabelEXT` commands are generated in `endEventLog()`, which is executed regardless of whether the low-level draw call is no-op'd, as happens in these cases for `glDrawElements()` when the count is zero (see `Context.inl.h`).

**Comment by mark-lunarg** [comment] 2021-05-19 16:32
This issue appears to be caused by a couple of ANGLE problems -- with PUBG Mobile it was due to `glDrawBuffer`* calls being handled incorrectly, and for Hillclimb it was due to the commandTree hierarchy tracking for aborted DrawCalls.  The PUBG fix has been pushed to ANGLE and the Hillclimb fix is in review.

**Comment by mark-lunarg** [comment] 2021-05-20 15:34
Both ANGLE fixes have been accepted and pushed and no action is required for AGI itself, so closing as resolved.

**Closed by mark-lunarg** 2021-05-20 15:34 UTC
