### ISSUE TITLE
ASUS ROG5 not supported in AGI validator

### ISSUE THREAD

**Issue by jackdannise** [google/agi#905] opened 2021-08-18 07:35 UTC
**Environment information:**
 - AGI version:
 - Host OS: [e.g. Linux] 
 If tracing on Android:
 - Device model: ASUS_I005DC
 - Android Version: A11

**Bug description**
AGI UI says valifation failed

**Reproduction steps**

**Stacktrace**
Please paste a stacktrace here if it's available.

**Screenshots**

**Additional debugging information**
- Please attach the generated _gapis.log_ and _gapic.log_ files you will find in the temp folder (e.g. /tmp/ on linux).
- If using Android: Please attach a full logcat dump (```adb logcat -d > logcat-full.txt```) that contains logs since AGI was started.

**Comment by pmuetschard** [comment] 2021-09-20 17:15
Duplicate of https://github.com/google/agi/issues/813

**Closed by pmuetschard** 2021-09-20 17:15 UTC
Labels: Device Support
