### ISSUE TITLE
Samsung Galaxy S21 validation fails

### ISSUE THREAD

**Issue by JeffreyLeeExient** [google/agi#1181] opened 2022-08-22 11:00 UTC
**Environment information:**
 - AGI version: 2022-3.0.1:d7f82c3dda2df3d81e7b67157da8668c4242511c
 - Host OS: macOS 12.5.1
 If tracing on Android:
 - Device model: Samsung Galaxy S21 FE 5G (SM-G990B/DS)
 - Android Version: 12

**Bug description**
Device validation fails for all capture types.

**Reproduction steps**
Connect the device via USB and attempt validation.

**Screenshots**
![Screenshot 2022-08-22 at 11 51 37](https://user-images.githubusercontent.com/107552420/185905271-a54bf7ce-e9f9-47d5-b5a5-dbd39e819d87.png)

**Additional debugging information**
* [gapis.log](https://github.com/google/agi/files/9393713/gapis.log)
* [gapic.log](https://github.com/google/agi/files/9393715/gapic.log)
* [logcat-full.txt](https://github.com/google/agi/files/9393717/logcat-full.txt)
* [validation590881498.perfetto.zip](https://github.com/google/agi/files/9393719/validation590881498.perfetto.zip)

**Comment by ttanatb** [comment] 2022-08-22 14:17
Hi, thanks for submitting this issue! Looking at the trace you've provided, it seems like this is the same issue as https://github.com/google/agi/issues/1113 (all the values for every GPU counter is at 0). This happened due to security patch that broke AGI. Unfortunately, access to GPU counters on Samsung devices w/ Qualcomm GPU currently requires the phone to be rooted. Folks at Samsung has already been notified of this issue and we're working to get this mended in a patch as soon as possible.

I'm going to close this issue because it's a duplicate, feel free to add to the thread in https://github.com/google/agi/issues/1113 if you have more questions/suggestions/comments regarding the topic

**Closed by ttanatb** 2022-08-22 14:17 UTC

**Comment by ttanatb** [comment] 2022-08-22 14:19
Duplicate of #1113
